version: '3.8'

x-project:
  name: "opcua-to-rest"

services:
  opcrouter:
    image: opcrouter/runtime:5.2
    environment:
      - OR_DISABLE_AUTH=true
      - OR_I_ACCEPT_EULA=true
      - OR_IMPORT_SOURCE=/inray/project.rpe
      - INITIAL_USERNAME=${INITIAL_USERNAME}
      - INITIAL_PASSWORD=${INITIAL_PASSWORD}
    ports:
      - "40201:8080"
    networks:
      - opcua-to-rest-stack-network
    volumes:
      - opcrouter-data:/data
      - opcrouter-config:/inray

  opc-ua-plc:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    command: "--autoaccept --veryfastrate=50"
    networks:
      - opcua-to-rest-stack-network

  webhook-tester:
    image: nginxdemos/hello:latest
    ports:
      - "40202:80"
    networks:
      - opcua-to-rest-stack-network

  init-config:
    image: alpine
    command: >
      sh -c "apk add git && 
             git clone https://github.com/BoBiene/opc-router-portainer-templates /tmp/repo &&
             cp /tmp/repo/opcua-to-rest/config/opc-router.rpe /inray/project.rpe"
    volumes:
      - opcrouter-config:/inray
    networks:
      - opcua-to-rest-stack-network

networks:
  opcua-to-rest-stack-network:

volumes:
  opcrouter-config:
  opcrouter-data:
