version: '3.8'

x-project:
  name: "opcua-to-rest"

services:
  opcrouter:
    image: opcrouter/runtime:5.2
    environment:
      - OR_DISABLE_AUTH=true
      - OR_I_ACCEPT_EULA=true
      - OR_IMPORT_SOURCE=/inray/project.rpe
      - INITIAL_USERNAME=${INITIAL_USERNAME}
      - INITIAL_PASSWORD=${INITIAL_PASSWORD}
    ports:
      - "40281:8080"
    networks:
      - stack-network
    volumes:
      - opcrouter-data:/data
      - opcrouter-config:/inray

  opc-ua-plc:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    command: "--autoaccept --veryfastrate=50"
    networks:
      - stack-network
  
  webhook-tester:
    image: nginxdemos/hello:latest
    ports:
      - "40282:80"
    networks:
      - stack-network

  nginx:
    image: nginx:latest
    ports:
      - "40280:80"
    volumes:
      - dashboard:/usr/share/nginx/html:ro
    networks:
      - stack-network
    depends_on:
      - init-config

  init-config:
    image: alpine
    command: >
      sh -c "apk add git && 
             git clone https://github.com/BoBiene/opc-router-portainer-templates /tmp/repo &&
             cp /tmp/repo/opcua-to-rest/config/opc-router.rpe /inray/project.rpe"&&
             cp -r /tmp/repo/opcua-to-influx/config/dashboard/* /dashboard/"
    volumes:
      - opcrouter-config:/inray
      - dashboard:/dashboard
    networks:
      - stack-network

networks:
  stack-network:

volumes:
  opcrouter-config:
  opcrouter-data:
  dashboard:
